if(this.getField('rater').value == 'Yes') {
	// selected
	this.getField('Zone_Hide').display = display.hidden;
} else {
	// Not Required
	this.getField('Zone_Hide').display = display.visible;
	this.getField('AF_Hide').display = display.visible;
	this.getField('Zone_Count').value = 1;

}
var ManoMake;
var ManoModel;
var ManoSerial;
var FlowHoodMake;
var FlowHoodModel;
var FlowHoodSerial;
var FlowGridMake;
var FlowGridModel;
var FlowGridSerial;
var BDFanMake;
var BDFanModel;
var BDFanSerial;
var RCMGaugeMake;
var RCMGaugeModel;
var RCMGaugeSerial;
switch (this.getField('rater').value) {
    case 'Abran Jimenez':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '3644-7-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10137';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;    
    case 'Adrian Hires':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '3460-4-700';
		FlowHoodMake = 'Testo';
		FlowHoodModel = '420';
		FlowHoodSerial = 'AF0317-17';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Chase Allen':
        ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Chris Stewart':
        ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Colin Hutchison':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG1000 / DG-700';
		ManoSerial = '2722 / 3572-5-700';
		FlowHoodMake = 'Testo';
		FlowHoodModel = '420';
		FlowHoodSerial = '50605400';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-1625 / 20-1642';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '27112';
		RCMGaugeMake = 'Field Piece';
		RCMGaugeModel = 'Job Link';
		RCMGaugeSerial ='6979-3979-0979-6980-3980-0980';
        break;
    case 'Estephen Zuniga':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '33207-7-700';
		FlowHoodMake = 'Accubalance';
		FlowHoodModel = '8371';
		FlowHoodSerial = '71215590';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-3219 / 20-3219';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '10689';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A10695';
        break;
    case 'Harry Williams':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG1000';
		ManoSerial = '235';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10127';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '20-2407';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '15382';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A10261';
        break;
    case 'Jacob Paradela':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '24385-7-700';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Jose Galvan':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '41173-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10128';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-2592 / 20-2587';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '12786';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A13557';
        break;
    case 'Julio Medina':
        ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Mark Souza':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '38496-7-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10141';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-2822 / 20-2855';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '9915';
		RCMGaugeMake = 'Field Piece';
		RCMGaugeModel = 'sman2';
		RCMGaugeSerial ='12000114';
        break;
    case 'Matt Griffin':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '9986-7-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10386';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-3106 / 20-3106';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '12476';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A11918';
        break;
    case 'Niko Rodriguez':
        ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Raymond Espudo':
        ManoMake = 'RetroTec';
		ManoModel = 'DM-2';
		ManoSerial = '208314';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10273';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '1706-5-700';
		BDFanMake = 'RetroTec';
		BDFanModel = '1000F';
		BDFanSerial = '208314';
		RCMGaugeMake = 'Field Piece';
		RCMGaugeModel = 'sman3';
		RCMGaugeSerial ='12000408';
        break;
    case 'Richard Swingle':
       	ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '10788-700';
		FlowHoodMake = 'Kano Max';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10128';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-3115 / 20-3115';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '15727';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900m';
		RCMGaugeSerial ='A13415';
        break;
    case 'Sam Maimone':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '4779-5-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10257';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '612-827-1117';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '27651';
		RCMGaugeMake = 'Field Piece';
		RCMGaugeModel = 'sman3';
		RCMGaugeSerial ='11009591';
        break;
    case 'Sean O Day':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '6795-4-700';
		FlowHoodMake = 'KanoMax';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10130';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-1626 / 20-1643';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '28038';
		RCMGaugeMake = 'Field Piece / iManifold';
		RCMGaugeModel = 'sman3 / 900M';
		RCMGaugeSerial ='A11913 / 12001856';
        break;
    case 'Steven Khamou':
        ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Tim ONeil':
        ManoMake = 'RetroTec';
		ManoModel = 'DM-2';
		ManoSerial = '407719';
		FlowHoodMake = 'Testo';
		FlowHoodModel = '420';
		FlowHoodSerial = '50602826';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-1625';
		BDFanMake = 'RetroTec';
		BDFanModel = '5000';
		BDFanSerial = '100901';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A11155';
        break;
    case 'Tinya Lewis':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG-700';
		ManoSerial = '43307-7-700';
		FlowHoodMake = 'Testo';
		FlowHoodModel = '420';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';
        break;
    case 'Tony Souza':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG1000 / DG700 ';
		ManoSerial = '1404 / 28270-7-700';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-3585 / 20-3585';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '12619';
		RCMGaugeMake = 'Field Piece / iManifold / Field Piece';
		RCMGaugeModel = 'sman3 / 900M';
		RCMGaugeSerial ='12008408 / A11155 / 3885-6886-0886-0886-3886-3885';
        break;
    case 'Victor Cortinas':
        ManoMake = 'Energy Conservatory';
		ManoModel = 'DG700';
		ManoSerial = '4515-4-700';
		FlowHoodMake = 'Kano Max';
		FlowHoodModel = '6710';
		FlowHoodSerial = '10140';
		FlowGridMake = 'Energy Conservatory';
		FlowGridModel = 'TruFlow';
		FlowGridSerial = '14-2999 / 20-2468';
		BDFanMake = 'Energy Conservatory';
		BDFanModel = 'BD3';
		BDFanSerial = '29147';
		RCMGaugeMake = 'iManifold';
		RCMGaugeModel = '900M';
		RCMGaugeSerial ='A10027';
        break;
    default:
    	ManoMake = '';
		ManoModel = '';
		ManoSerial = '';
		FlowHoodMake = '';
		FlowHoodModel = '';
		FlowHoodSerial = '';
		FlowGridMake = '';
		FlowGridModel = '';
		FlowGridSerial = '';
		BDFanMake = '';
		BDFanModel = '';
		BDFanSerial = '';
		RCMGaugeMake = '';
		RCMGaugeModel = '';
		RCMGaugeSerial ='';

}

this.getField('Manometer_Make').value = ManoMake;
this.getField('Manometer_Model').value = ManoModel;
this.getField('Manometer_Serial').value = ManoSerial;
this.getField('FlowHood_Make').value = FlowHoodMake;
this.getField('FlowHood_Model').value = FlowHoodModel;
this.getField('FlowHood_Serial').value = FlowHoodSerial;
this.getField('FlowGrid_Make').value = FlowGridMake;
this.getField('FlowGrid_Model').value = FlowGridModel;
this.getField('FlowGrid_Serial').value = FlowGridSerial;
this.getField('BDFan_Make').value = BDFanMake;
this.getField('BDFan_Model').value = BDFanModel;
this.getField('BDFan_Serial').value = BDFanSerial;
this.getField('RCMGauge_Make').value = RCMGaugeMake;
this.getField('RCMGauge_Model').value = RCMGaugeModel;
this.getField('RCMGauge_Serial').value = RCMGaugeSerial;

